### ISSUE TITLE
NPE - org.jboss.forge.addon.ui.impl.controller.SingleCommandControllerImpl.initialize(SingleCommandControllerImpl.java:61)

### ISSUE THREAD

**Issue by cmoulliard** [openshiftio/launchpad-backend#47]
NPE is reported when we try to create a project using the button "Begin by selecting a runtime project framework (Eclipse Vert.x, WildFly Swarm, or Spring Boot)"
-->
https://gist.github.com/cmoulliard/3cab4b2d06fe274ceff8fbb98cb84a96#file-gistfile1-txt-L142

**Comment by gastaldi** [comment]
The starter no longer exists and will removed from the UI
