### ISSUE TITLE
Slow connection can result in failed deployment

### ISSUE THREAD

**Issue by SlavoKrupa** [openshiftio/launchpad-backend#56]
Indexing of repositories is considered in health check. If indexing takes too long (e.g. on slow Internet connection), it can result in health checks killing pod and failed deployment.

**Comment by gastaldi** [comment]
Timeout was increased in https://github.com/openshiftio/launchpad-backend/commit/8ae2ed1586aa37bee72c3b789490c4b8f3af7b04
